### ISSUE TITLE
what is design.xd?

### ISSUE THREAD

**Issue by Karyum** [FACN1/week7-ifitmake-suHapi#30]
design/design.xd

**Comment by philawsophizing** [comment]
adobe file? how can we open/view it? share your secrets elias!

**Comment by hibaakel** [comment]
i have the same question ?!!

**Comment by macintoshhelper** [comment]
Adobe Experience Design file (Adobe program designed for website/app UI) - it's free for beta, then will be a paid program. I should have exported an image that anyone can view too.

**Comment by macintoshhelper** [comment]
`Fixed` in https://github.com/FACN1/week7-ifitmake-suHapi/pull/50 (added normal image too)

**Comment by Karyum** [comment]
cheers!
