### ISSUE TITLE
indentation in home.js

### ISSUE THREAD

**Issue by jwld** [FACN1/week7-ifitmake-suHapi#32]
https://github.com/FACN1/week7-ifitmake-suHapi/blob/master/src/routes/home.js#L8-L11

**Comment by jwld** [comment]
🎉

**Comment by macintoshhelper** [comment]
😎

**Comment by macintoshhelper** [comment]
:mag:

**Comment by macintoshhelper** [comment]
Fixed in https://github.com/FACN1/week7-ifitmake-suHapi/pull/48 🎉🎉🎉🎉🎉🎉🎉🎉

**Comment by jwld** [comment]
:clap:
