### ISSUE TITLE
Is your search.hbs view ever actually used?

### ISSUE THREAD

**Issue by jwld** [FACN1/week7-ifitmake-suHapi#41]

**Comment by jwld** [comment]
Also I feel like you need more in your view files - your website is built entirely out of partials which seems odd

**Comment by m4v15** [comment]
I know what you mean, but kind of feel like this is the beauty of partials - the partials hold all the actual html code, but we put the different partials together in different ways in our views. That way the code is re-usable?

I might be totally wrong tho 🤷‍♂️

**Comment by m4v15** [comment]
But yeah in we ended up not using search.hbs

**Comment by macintoshhelper** [comment]
Fixed in https://github.com/FACN1/week7-ifitmake-suHapi/pull/51 - search.hbs is now used... - to fix another issue
